### ISSUE TITLE
composer installation doesn't work

### ISSUE THREAD

**Issue by Aziz-JH** [dmhendricks/file-icon-vectors#1]
Hey Daniel,
good job with the vector icons but the installation doesn't work for me.

I got this Error:
```
Could not find package dmhendricks/file-icon-vectors at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

- Composer version 1.5.2
- System Windows 10

Can you also add it to npm?

Best,
Julian

**Comment by dmhendricks** [comment]
Thank you. I didn't do a release yet - I will see if I can do that soon. You should be able to add `"minimum-stability": "dev"` to `composer.json` to get it to pull.

I will add it to npm eventually. I would probably like to resize the classic set to make them consistent first. If/when I had the time, this could be set up better.

**Comment by Aziz-JH** [comment]
ok thanks :)
