### ISSUE TITLE
[Icon Request] Generic File

### ISSUE THREAD

**Issue by BtM909** [dmhendricks/file-icon-vectors#17]
While you have so much extensions already covered, is it possible to add one generic file design? This could be used if no extension can be resolved, so at least the file icon looks like your style.

Microsoft's Fluent UI uses this for example:
- Docx: https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200515.001/assets/item-types/32/docx.svg
- Generic: https://spoprod-a.akamaihd.net/files/fabric-cdn-prod_20200515.001/assets/item-types/32/genericfile.svg

**Comment by zoffixznet** [comment]
I believe there is one already, called "blank": https://github.com/dmhendricks/file-icon-vectors/blob/master/dist/icons/classic/blank.svg

**Comment by BtM909** [comment]
Ah nice, I was looking for generic and unknown. Thanks!
