### ISSUE TITLE
TODO and Priorities

### ISSUE THREAD

**Issue by dmhendricks** [dmhendricks/file-icon-vectors#5]
There are so many things to tweak, fix and make consistent. There are so many icons to add. Time is precious.

My goal for release 0.9.0 is to get the current sets sync'd. There are about 60 icons not present among the sets.

**UPDATE 18 Jul 2018:** I'm down to 12 icons missing from Square Outline.

**Comment by dmhendricks** [comment]
- 0.9.1 is mostly going to include some optimizations and tweaks for various icons that I don't like, possibly better automation, and certainly several missing extensions.
- 1.0.0 might include a round (circular) or dark (designed for dark backgrounds) set. Feedback*?

*I feel like I already know the answer. Night mode. :smile:

**Comment by nicrf** [comment]
Can you add a Open Folder Icon?

**Comment by dmhendricks** [comment]
Version 1.0 has been released.

@nicrf - Sorry, I just saw this reply. I will add it to my list for the next release. Thank you.
